### ISSUE TITLE
Videos in .wmv are corrupted

### ISSUE THREAD

**Issue by Darken-kun** [jans0n/RewritePlusImprovementPatch#6]
<img width="651" alt="op00" src="https://user-images.githubusercontent.com/21168806/147378404-9e627b7e-aaec-4dfd-949a-568154edb1d9.png">
<img width="649" alt="ed00" src="https://user-images.githubusercontent.com/21168806/147378406-7fa9a032-fb14-4e5d-8f24-631889cfd078.png">
From what I tested, this happened after v1.5 patch.
Videos in .mpg format didn't get affected.

**Comment by jans0n** [comment]
They both play completely fine for me; it might be your video player. Try playing them with [mpv](https://mpv.io/). What happens when you try to play them in-game?
![image](https://user-images.githubusercontent.com/22122781/147378638-0f7c612e-4d50-44b9-b3a0-ec447562dead.png)
![image](https://user-images.githubusercontent.com/22122781/147378641-2f75adac-dec4-4eb6-b933-630a6b244724.png)

**Comment by Darken-kun** [comment]
Yeah, this video player did the trick. It seems it was some problem with the codec I was using. Thanks.
